sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5a854664d625_key -iv $encrypted_5a854664d625_iv -in github_deploy_key.enc -out github_deploy_key -d
- npm i -g npm
script:
- npm run test
- npm run build
- npm run build:example
after_success:
- npm run semantic-release
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: chmod +x $TRAVIS_BUILD/docs-deploy.sh && $TRAVIS_BUILD/docs-deploy.sh
    on:
      branch: master
