sudo: false
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '8'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
- npm run test
- npm run build
- npm run build:example
after_success:
- npm run semantic-release
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: chmod +x ./docs-deploy.sh && ./docs-deploy.sh
    on:
      branch: master
